packages:
  - apps/*
  - packages/shared/*
  - tooling/*

catalog:
  "@biomejs/biome": ^1.9.4
  "@tsconfig/strictest": ^2.0.5
  "@types/node": ^22.13.9
  tsup: ^8.4.0
  tsx: ^4.19.3
  typescript: ^5.8.2
